name: deploy dev


on:
  pull_request:
    branches: [ main ]

jobs:
  test-changes:
    runs-on: ubuntu-latest
    name: build/test
    steps:
      - uses: actions/checkout@v2

      - name: npm - install Dependencies
        if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
        run: 'npm install'

      - name: Run Test
        run: |
          npm run test

  deploy-env:
    name: deploy lamda
    runs-on: ubuntu-latest
    needs: testing-changes
    steps:
    - uses: actions/checkout@v2.0.0

    - name: npm - load cached env
      id: cached-npm-dependencies
      uses: actions/cached@v2
      with:
        path: node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: npm - install Dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'


    - name: deploy using sls
      run: 'npx sls deploy'
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: comment PR
      uses: thollander/actions-comment-pull-request@v1
      with: 
        message: |
          Your app was deployed